name: Build and Release Edgeble linux-next

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    name: Edgeble linux-next runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Clone and Compile
        run: |
          git clone git@gitlab.com:edgeble/core/linux-next.git && cd linux-next
          export CROSS_COMPILE=/tools/arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-
          ARCH=arm64 make rockchip_linux_defconfig gpu.config edgeble-6tops.config
          mkdir -p ${{ github.workspace }}/out
          mkdir -p ${{ github.workspace }}/out/linux-next
          mkdir -p ${{ github.workspace }}/out/dtb/rockchip
          mkdir -p ${{ github.workspace }}/out/modules-next
          ARCH=arm64 make dtbs Image -j 16; ARCH=arm64 make modules -j 16; ARCH=arm64 make modules_install INSTALL_MOD_PATH=${{ github.workspace }}/out

      - name: Copy deb files and create archive
        run: |
          echo "Copy DTB:"
          cp -fv ${{ github.workspace }}/linux-next/arch/arm64/boot/dts/rockchip/rk3588-edgeble-*.dtb ${{ github.workspace }}/out/dtb/rockchip
          cp -fv ${{ github.workspace }}/linux-next/arch/arm64/boot/dts/rockchip/rk3588-edgeble-*.dtbo ${{ github.workspace }}/out/dtb/rockchip
          cp -fv ${{ github.workspace }}/linux-next/arch/arm64/boot/dts/rockchip/rk3588-rock-5b.dtb ${{ github.workspace }}/out/dtb/rockchip

          echo "Copy config:"
          cp -fv ${{ github.workspace }}/linux-next/.config ${{ github.workspace }}/out/linux-next

          echo "Create linux-next:"
          cp -frv ${{ github.workspace }}/linux-next/arch/arm64/boot/Image ${{ github.workspace }}/out/dtb ${{ github.workspace }}/out/linux-next

          echo "Create modules-next:"
          cp -frv ${{ github.workspace }}/out/lib/modules/* ${{ github.workspace }}/out/modules-next

          echo "Create tar.xz"
          cd ${{ github.workspace }}/out/
          tar -Jcf linux-next.tar.xz linux-next && tar -Jcf modules-next.tar.xz modules-next

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v1.0"
          body: |
            - Add HDMI1 Out
          files: |
            ${{ github.workspace }}/out/linux-next.tar.xz
            ${{ github.workspace }}/out/modules-next.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
