name: Build and Release Edgeble linux-next

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    name: Edgeble linux-next runner
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Clone and Compile
        run: |
          cd /tops/linux-next
          rm -rf /tops/out && rm -rf linux-next* && rm -rf modules-next*
          export CROSS_COMPILE=/tools/arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-
          ARCH=arm64 make defconfig
          ARCH=arm64 make dtbs Image -j 16; ARCH=arm64 make modules -j 16; ARCH=arm64 make modules_install INSTALL_MOD_PATH=/tops/out

      - name: Copy deb files and create archive
        run: |
          echo "Present Working Directory"
          cd /tops/linux-next
          mkdir linux-next && mkdir -p dtb/rockchip && mkdir -p modules-next
          cp -fv arch/arm64/boot/dts/rockchip/rk3588-edgeble-*.dtb dtb/rockchip
          cp -fv arch/arm64/boot/dts/rockchip/rk3588-edgeble-*.dtbo dtb/rockchip
          cp -fv arch/arm64/boot/dts/rockchip/rk3588-rock-5b.dtb dtb/rockchip
          cp -fv .config linux-next
          cp -frv arch/arm64/boot/Image dtb linux-next
          tar -Jcf linux-next.tar.xz linux-next
          cp -frv /tops/out/lib/modules/* modules-next
          tar -Jcf modules-next.tar.xz modules-next

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v1.2"
          body: |
            - Add HDMI1 Out
          files: |
            /tops/linux-next/linux-next.tar.xz
            /tops/linux-next/modules-next.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
